In [ ]:
# Name: Shreyas Wani PRN: 25070123131
# Experiment 15
# Aim: Data Normalization and Data type Conversion

In [ ]:
# Dataset
import pandas as pd
import numpy as np

data = {'Product':['Laptop','Mobile','Tablet','Headphones','Smartwatch','Camera'], 'Price':[55000,20000,30000,2000,8000,45000], 'Units_Sold':[25,60,35,80,50,15], 'Discount':[10,15,12,20,18,8]}

df = pd.DataFrame(data)
print(df)

      Product  Price  Units_Sold  Discount
0      Laptop  55000          25        10
1      Mobile  20000          60        15
2      Tablet  30000          35        12
3  Headphones   2000          80        20
4  Smartwatch   8000          50        18
5      Camera  45000          15         8

In [ ]:
# Min-Max Normalization
# Min-Max Normalization for price
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
print(df[['Product','Price','Price_MinMax']])

      Product  Price  Price_MinMax
0      Laptop  55000      1.000000
1      Mobile  20000      0.339623
2      Tablet  30000      0.528302
3  Headphones   2000      0.000000
4  Smartwatch   8000      0.113208
5      Camera  45000      0.811321

In [ ]:
# Normalize Multiple Columns
cols = ['Price','Units_Sold','Discount']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
print(df_norm)

      Price  Units_Sold  Discount
0  1.000000    0.153846  0.166667
1  0.339623    0.692308  0.583333
2  0.528302    0.307692  0.333333
3  0.000000    1.000000  1.000000
4  0.113208    0.538462  0.833333
5  0.811321    0.000000  0.000000

In [ ]:
# Z-score Normalization
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
print(df[['Product', 'Units_Sold', "Units_Zscore"]])

      Product  Units_Sold  Units_Zscore
0      Laptop          25     -0.799885
1      Mobile          60      0.660775
2      Tablet          35     -0.382554
3  Headphones          80      1.495437
4  Smartwatch          50      0.243443
5      Camera          15     -1.217216

In [ ]:
# Decimal Scaling
df['Price_Decimal'] = df['Price']/100000
print(df[['Product','Price','Price_Decimal']])

      Product  Price  Price_Decimal
0      Laptop  55000           0.55
1      Mobile  20000           0.20
2      Tablet  30000           0.30
3  Headphones   2000           0.02
4  Smartwatch   8000           0.08
5      Camera  45000           0.45

In [ ]:
df['Discount_Decimal'] = df['Price']/100
print(df[['Product','Price','Discount_Decimal']])

      Product  Price  Discount_Decimal
0      Laptop  55000             550.0
1      Mobile  20000             200.0
2      Tablet  30000             300.0
3  Headphones   2000              20.0
4  Smartwatch   8000              80.0
5      Camera  45000             450.0

In [ ]:
#Dataset
import pandas as pd
import numpy as np
data = {
'Order_ID':[101,102,103,104,105,106],
'Customer_Gender':['Male','Female','Female','Male','Female','Male'],
'Payment_Method':['UPI','Credit Card','Debit Card','COD','UPI','Debit Card'],
'Product_Category':['Electronics','Clothing','Home','Electronics','Beauty','Electronics'],
'City':['Pune','Mumbai','Delhi','Bangalore','Pune','Hyderabad'],
'Order_Value':[4500,2300,3200,5200,1800,4100]
}
df = pd.DataFrame(data)
display(df)

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value
0,101,Male,UPI,Electronics,Pune,4500
1,102,Female,Credit Card,Clothing,Mumbai,2300
2,103,Female,Debit Card,Home,Delhi,3200
3,104,Male,COD,Electronics,Bangalore,5200
4,105,Female,UPI,Beauty,Pune,1800
5,106,Male,Debit Card,Electronics,Hyderabad,4100

In [ ]:
# Method 1 : Label Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Gender_Label'] = le.fit_transform(df['Customer_Gender'])
df['City_Label'] = le.fit_transform(df['City'])
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label
0,101,Male,UPI,Electronics,Pune,4500,1,4
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,3
2,103,Female,Debit Card,Home,Delhi,3200,0,1
3,104,Male,COD,Electronics,Bangalore,5200,1,0
4,105,Female,UPI,Beauty,Pune,1800,0,4
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2

In [ ]:
# Method 2: One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=['Payment_Method'])
df_encoded

,Order_ID,Customer_Gender,Product_Category,City,Order_Value,Gender_Label,City_Label,Payment_Method_COD,Payment_Method_Credit Card,Payment_Method_Debit Card,Payment_Method_UPI
0,101,Male,Electronics,Pune,4500,1,4,False,False,False,True
1,102,Female,Clothing,Mumbai,2300,0,3,False,True,False,False
2,103,Female,Home,Delhi,3200,0,1,False,False,True,False
3,104,Male,Electronics,Bangalore,5200,1,0,True,False,False,False
4,105,Female,Beauty,Pune,1800,0,4,False,False,False,True
5,106,Male,Electronics,Hyderabad,4100,1,2,False,False,True,False

In [ ]:
# Encoding Multiple Columns
df_multi = pd.get_dummies(df, columns=['Customer_Gender','Product_Category','City'])
df_multi

,Order_ID,Payment_Method,Order_Value,Gender_Label,City_Label,Customer_Gender_Female,Customer_Gender_Male,Product_Category_Beauty,Product_Category_Clothing,Product_Category_Electronics,Product_Category_Home,City_Bangalore,City_Delhi,City_Hyderabad,City_Mumbai,City_Pune
0,101,UPI,4500,1,4,False,True,False,False,True,False,False,False,False,False,True
1,102,Credit Card,2300,0,3,True,False,False,True,False,False,False,False,False,True,False
2,103,Debit Card,3200,0,1,True,False,False,False,False,True,False,True,False,False,False
3,104,COD,5200,1,0,False,True,False,False,True,False,True,False,False,False,False
4,105,UPI,1800,0,4,True,False,True,False,False,False,False,False,False,False,True
5,106,Debit Card,4100,1,2,False,True,False,False,True,False,False,False,True,False,False

In [ ]:
# Method 3: Dummy Encoding (Drop First)
df_dummy = pd.get_dummies(df, columns = ['Payment_Method', 'City', 'Payment_Method','Product_Category'], drop_first=True)
df

,Order_ID,Customer_Gender,Payment_Method,Product_Category,City,Order_Value,Gender_Label,City_Label
0,101,Male,UPI,Electronics,Pune,4500,1,4
1,102,Female,Credit Card,Clothing,Mumbai,2300,0,3
2,103,Female,Debit Card,Home,Delhi,3200,0,1
3,104,Male,COD,Electronics,Bangalore,5200,1,0
4,105,Female,UPI,Beauty,Pune,1800,0,4
5,106,Male,Debit Card,Electronics,Hyderabad,4100,1,2

In [ ]:
# Data Normalization
import pandas as pd
df = pd.read_csv('/content/amazon_products_dataset_Expt-14 (1).csv')
df

   Product_ID                 Product_Name  Price  Rating  Reviews  Units_Sold
0        P101               Wireless Mouse    799     4.3     1520         350
1        P102            Bluetooth Speaker   1499     4.5      980         220
2        P103                 USB Keyboard    699     4.1      870         180
3        P104               Gaming Headset   2499     4.6     2100         410
4        P105                   Smartwatch   3999     4.4     3050         520
5        P106                   Power Bank   1199     4.2     1750         390
6        P107                 Laptop Stand    899     4.0      620         140
7        P108                       Webcam   1899     4.3     1120         260
8        P109                 Portable SSD   5499     4.7     1850         330
9        P110             Wireless Charger    999     4.2      760         190
10       P111  Noise Cancelling Headphones   7999     4.6     4200         610
11       P112          Mechanical Keyboard   4599     4.5     2100         290
12       P113                 Gaming Mouse   1599     4.4     1300         340
13       P114                 Tablet Stand    699     4.1      540         120
14       P115                      USB Hub    899     4.2      870         200
15       P116          External Hard Drive   6499     4.6     2300         310
16       P117            Smartphone Tripod   1199     4.3      760         210
17       P118              Laptop Backpack   1999     4.4     1600         420
18       P119            Bluetooth Earbuds   2999     4.5     3500         530
19       P120                LED Desk Lamp   1299     4.3      980         260
20       P121                 Phone Holder    499     4.0      420         150
21       P122            Wireless Keyboard   2499     4.4     1450         310
22       P123             Portable Monitor   8999     4.6     1250         170
23       P124                   Smart Plug    799     4.2      720         210
24       P125                  WiFi Router   3499     4.5     2100         390
25       P126              Graphics Tablet   4599     4.4      980         160
26       P127                   VR Headset  12999     4.7     3100         140
27       P128                   Microphone   2199     4.3     1300         270
28       P129             Smart Light Bulb    699     4.2      880         240
29       P130           Laptop Cooling Pad   1499     4.3      990         260
30       P131                Action Camera   9999     4.6     2100         200
31       P132               Smart Doorbell   5999     4.5     1750         180
32       P133              Streaming Stick   3499     4.4     2500         430
33       P134           Portable Projector  11999     4.6     1450         120
34       P135                 Gaming Chair  15999     4.7     2100          90
35       P136               Desk Organizer    599     4.1      450         160
36       P137              USB Flash Drive    799     4.2      900         320
37       P138       Phone Screen Protector    299     4.0      600         380
38       P139                Laptop Sleeve    999     4.3      720         210
39       P140           Wireless Presenter   1499     4.4      520         130
40       P141         Tablet Keyboard Case   2999     4.5      850         150
41       P142             Smart Thermostat  10999     4.6     1200         110
42       P143              Security Camera   4999     4.4     2100         260
43       P144                 Drone Camera  24999     4.7     1800          70
44       P145              Electric Kettle   1999     4.3     1400         310
45       P146                    Air Fryer   7999     4.6     2200         200
46       P147                 Robot Vacuum  18999     4.5     1650         120
47       P148                  Smart Scale   2499     4.4      980         170
48       P149          Digital Photo Frame   3499     4.3      870         150
49       P150                 Portable Fan    999     4.2      760         240

In [ ]:
# Min-Max Normalization
df['Price_MinMax'] = (df['Price'] - df['Price'].min()) / (df['Price'].max() - df['Price'].min())
display(df[['Product_ID','Price','Price_MinMax']])

   Product_ID  Price  Price_MinMax
0        P101    799      0.020243
1        P102   1499      0.048583
2        P103    699      0.016194
3        P104   2499      0.089069
4        P105   3999      0.149798
5        P106   1199      0.036437
6        P107    899      0.024291
7        P108   1899      0.064777
8        P109   5499      0.210526
9        P110    999      0.028340
10       P111   7999      0.311741
11       P112   4599      0.174089
12       P113   1599      0.052632
13       P114    699      0.016194
14       P115    899      0.024291
15       P116   6499      0.251012
16       P117   1199      0.036437
17       P118   1999      0.068826
18       P119   2999      0.109312
19       P120   1299      0.040486
20       P121    499      0.008097
21       P122   2499      0.089069
22       P123   8999      0.352227
23       P124    799      0.020243
24       P125   3499      0.129555
25       P126   4599      0.174089
26       P127  12999      0.514170
27       P128   2199      0.076923
28       P129    699      0.016194
29       P130   1499      0.048583
30       P131   9999      0.392713
31       P132   5999      0.230769
32       P133   3499      0.129555
33       P134  11999      0.473684
34       P135  15999      0.635628
35       P136    599      0.012146
36       P137    799      0.020243
37       P138    299      0.000000
38       P139    999      0.028340
39       P140   1499      0.048583
40       P141   2999      0.109312
41       P142  10999      0.433198
42       P143   4999      0.190283
43       P144  24999      1.000000
44       P145   1999      0.068826
45       P146   7999      0.311741
46       P147  18999      0.757085
47       P148   2499      0.089069
48       P149   3499      0.129555
49       P150    999      0.028340

In [ ]:
# Z-Score Normalization
df['Units_Zscore'] = (df['Units_Sold'] - df['Units_Sold'].mean()) / df['Units_Sold'].std()
display(df[['Product_ID','Units_Sold','Units_Zscore']])

   Product_ID  Units_Sold  Units_Zscore
0        P101         350      0.812282
1        P102         220     -0.260855
2        P103         180     -0.591051
3        P104         410      1.307576
4        P105         520      2.215615
5        P106         390      1.142478
6        P107         140     -0.921247
7        P108         260      0.069341
8        P109         330      0.647184
9        P110         190     -0.508502
10       P111         610      2.958556
11       P112         290      0.316988
12       P113         340      0.729733
13       P114         120     -1.086345
14       P115         200     -0.425953
15       P116         310      0.482086
16       P117         210     -0.343404
17       P118         420      1.390125
18       P119         530      2.298164
19       P120         260      0.069341
20       P121         150     -0.838698
21       P122         310      0.482086
22       P123         170     -0.673600
23       P124         210     -0.343404
24       P125         390      1.142478
25       P126         160     -0.756149
26       P127         140     -0.921247
27       P128         270      0.151890
28       P129         240     -0.095757
29       P130         260      0.069341
30       P131         200     -0.425953
31       P132         180     -0.591051
32       P133         430      1.472674
33       P134         120     -1.086345
34       P135          90     -1.333992
35       P136         160     -0.756149
36       P137         320      0.564635
37       P138         380      1.059929
38       P139         210     -0.343404
39       P140         130     -1.003796
40       P141         150     -0.838698
41       P142         110     -1.168894
42       P143         260      0.069341
43       P144          70     -1.499090
44       P145         310      0.482086
45       P146         200     -0.425953
46       P147         120     -1.086345
47       P148         170     -0.673600
48       P149         150     -0.838698
49       P150         240     -0.095757

In [ ]:
# Normalize Multiple Columns
cols = ['Price','Units_Sold','Rating','Reviews']
df_norm = (df[cols] - df[cols].min()) / (df[cols].max() - df[cols].min())
df_norm

       Price  Units_Sold    Rating   Reviews
0   0.020243    0.518519  0.428571  0.291005
1   0.048583    0.277778  0.714286  0.148148
2   0.016194    0.203704  0.142857  0.119048
3   0.089069    0.629630  0.857143  0.444444
4   0.149798    0.833333  0.571429  0.695767
5   0.036437    0.592593  0.285714  0.351852
6   0.024291    0.129630  0.000000  0.052910
7   0.064777    0.351852  0.428571  0.185185
8   0.210526    0.481481  1.000000  0.378307
9   0.028340    0.222222  0.285714  0.089947
10  0.311741    1.000000  0.857143  1.000000
11  0.174089    0.407407  0.714286  0.444444
12  0.052632    0.500000  0.571429  0.232804
13  0.016194    0.092593  0.142857  0.031746
14  0.024291    0.240741  0.285714  0.119048
15  0.251012    0.444444  0.857143  0.497354
16  0.036437    0.259259  0.428571  0.089947
17  0.068826    0.648148  0.571429  0.312169
18  0.109312    0.851852  0.714286  0.814815
19  0.040486    0.351852  0.428571  0.148148
20  0.008097    0.148148  0.000000  0.000000
21  0.089069    0.444444  0.571429  0.272487
22  0.352227    0.185185  0.857143  0.219577
23  0.020243    0.259259  0.285714  0.079365
24  0.129555    0.592593  0.714286  0.444444
25  0.174089    0.166667  0.571429  0.148148
26  0.514170    0.129630  1.000000  0.708995
27  0.076923    0.370370  0.428571  0.232804
28  0.016194    0.314815  0.285714  0.121693
29  0.048583    0.351852  0.428571  0.150794
30  0.392713    0.240741  0.857143  0.444444
31  0.230769    0.203704  0.714286  0.351852
32  0.129555    0.666667  0.571429  0.550265
33  0.473684    0.092593  0.857143  0.272487
34  0.635628    0.037037  1.000000  0.444444
35  0.012146    0.166667  0.142857  0.007937
36  0.020243    0.462963  0.285714  0.126984
37  0.000000    0.574074  0.000000  0.047619
38  0.028340    0.259259  0.428571  0.079365
39  0.048583    0.111111  0.571429  0.026455
40  0.109312    0.148148  0.714286  0.113757
41  0.433198    0.074074  0.857143  0.206349
42  0.190283    0.351852  0.571429  0.444444
43  1.000000    0.000000  1.000000  0.365079
44  0.068826    0.444444  0.428571  0.259259
45  0.311741    0.240741  0.857143  0.470899
46  0.757085    0.092593  0.714286  0.325397
47  0.089069    0.185185  0.571429  0.148148
48  0.129555    0.148148  0.428571  0.119048
49  0.028340    0.314815  0.285714  0.089947

In [ ]:
# Decimal Scaling-Review/Price
df['Price_Decimal'] = df['Price'] / 100000

display("\nDecimal Scaling")
display(df[['Product_ID','Price','Price_Decimal']])

'\nDecimal Scaling'

   Product_ID  Price  Price_Decimal
0        P101    799        0.00799
1        P102   1499        0.01499
2        P103    699        0.00699
3        P104   2499        0.02499
4        P105   3999        0.03999
5        P106   1199        0.01199
6        P107    899        0.00899
7        P108   1899        0.01899
8        P109   5499        0.05499
9        P110    999        0.00999
10       P111   7999        0.07999
11       P112   4599        0.04599
12       P113   1599        0.01599
13       P114    699        0.00699
14       P115    899        0.00899
15       P116   6499        0.06499
16       P117   1199        0.01199
17       P118   1999        0.01999
18       P119   2999        0.02999
19       P120   1299        0.01299
20       P121    499        0.00499
21       P122   2499        0.02499
22       P123   8999        0.08999
23       P124    799        0.00799
24       P125   3499        0.03499
25       P126   4599        0.04599
26       P127  12999        0.12999
27       P128   2199        0.02199
28       P129    699        0.00699
29       P130   1499        0.01499
30       P131   9999        0.09999
31       P132   5999        0.05999
32       P133   3499        0.03499
33       P134  11999        0.11999
34       P135  15999        0.15999
35       P136    599        0.00599
36       P137    799        0.00799
37       P138    299        0.00299
38       P139    999        0.00999
39       P140   1499        0.01499
40       P141   2999        0.02999
41       P142  10999        0.10999
42       P143   4999        0.04999
43       P144  24999        0.24999
44       P145   1999        0.01999
45       P146   7999        0.07999
46       P147  18999        0.18999
47       P148   2499        0.02499
48       P149   3499        0.03499
49       P150    999        0.00999

In [ ]:
# Turning categorical variables into quantitative variables
import pandas as pd
df = pd.read_csv('/content/Student-Dataset.csv')
df

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary
0,101,Female,Computer,8.2,0,92,Placed,450000
1,102,Male,IT,7.5,1,85,Not Placed,0
2,103,Female,ENTC,9.1,0,96,Placed,550000
3,104,Male,Mechanical,6.8,2,78,Not Placed,0
4,105,Female,Computer,8.7,0,88,Placed,480000
5,106,Male,Civil,7.2,3,72,Not Placed,0
6,107,Female,IT,8.9,0,91,Placed,500000
7,108,Male,Computer,6.5,1,80,Not Placed,0
8,109,Female,ENTC,7.8,0,84,Placed,420000
9,110,Male,Mechanical,7.0,2,76,Not Placed,0

In [ ]:
# Label Encoding-Placement Status
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['Placement_Status_Label'] = le.fit_transform(df['Placement_Status'])
display(df)

,Roll_No,Gender,Department,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_Label,Placement_Status_Label
0,101,Female,Computer,8.2,0,92,Placed,450000,0,1
1,102,Male,IT,7.5,1,85,Not Placed,0,1,0
2,103,Female,ENTC,9.1,0,96,Placed,550000,0,1
3,104,Male,Mechanical,6.8,2,78,Not Placed,0,1,0
4,105,Female,Computer,8.7,0,88,Placed,480000,0,1
5,106,Male,Civil,7.2,3,72,Not Placed,0,1,0
6,107,Female,IT,8.9,0,91,Placed,500000,0,1
7,108,Male,Computer,6.5,1,80,Not Placed,0,1,0
8,109,Female,ENTC,7.8,0,84,Placed,420000,0,1
9,110,Male,Mechanical,7.0,2,76,Not Placed,0,1,0

In [ ]:
# One Hot Encoding- Department
df_encoded = pd.get_dummies(df, columns=['Department'])
display(df_encoded)

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_Label,Placement_Status_Label,Department_Civil,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,0,1,False,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,1,0,False,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,0,1,False,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,1,0,False,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,0,1,False,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,1,0,True,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,0,1,False,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,1,0,False,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,0,1,False,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,1,0,False,False,False,False,True

In [ ]:
# Encoding Multiple Columns
df_multi = pd.get_dummies(df, columns=['Number_of_Backlogs','Attendance_Percentage','Placement_Status'])
display(df_multi)

,Roll_No,Gender,Department,CGPA,Salary,Gender_Label,Placement_Status_Label,Number_of_Backlogs_0,Number_of_Backlogs_1,Number_of_Backlogs_2,...,Attendance_Percentage_78,Attendance_Percentage_80,Attendance_Percentage_84,Attendance_Percentage_85,Attendance_Percentage_88,Attendance_Percentage_91,Attendance_Percentage_92,Attendance_Percentage_96,Placement_Status_Not Placed,Placement_Status_Placed
0,101,Female,Computer,8.2,450000,0,1,True,False,False,...,False,False,False,False,False,False,True,False,False,True
1,102,Male,IT,7.5,0,1,0,False,True,False,...,False,False,False,True,False,False,False,False,True,False
2,103,Female,ENTC,9.1,550000,0,1,True,False,False,...,False,False,False,False,False,False,False,True,False,True
3,104,Male,Mechanical,6.8,0,1,0,False,False,True,...,True,False,False,False,False,False,False,False,True,False
4,105,Female,Computer,8.7,480000,0,1,True,False,False,...,False,False,False,False,True,False,False,False,False,True
5,106,Male,Civil,7.2,0,1,0,False,False,False,...,False,False,False,False,False,False,False,False,True,False
6,107,Female,IT,8.9,500000,0,1,True,False,False,...,False,False,False,False,False,True,False,False,False,True
7,108,Male,Computer,6.5,0,1,0,False,True,False,...,False,True,False,False,False,False,False,False,True,False
8,109,Female,ENTC,7.8,420000,0,1,True,False,False,...,False,False,True,False,False,False,False,False,False,True
9,110,Male,Mechanical,7.0,0,1,0,False,False,True,...,False,False,False,False,False,False,False,False,True,False

In [ ]:
# Dummies -Department
df_dummy = pd.get_dummies(df, columns=['Department'], drop_first=True)

display(df_dummy)

,Roll_No,Gender,CGPA,Number_of_Backlogs,Attendance_Percentage,Placement_Status,Salary,Gender_Label,Placement_Status_Label,Department_Computer,Department_ENTC,Department_IT,Department_Mechanical
0,101,Female,8.2,0,92,Placed,450000,0,1,True,False,False,False
1,102,Male,7.5,1,85,Not Placed,0,1,0,False,False,True,False
2,103,Female,9.1,0,96,Placed,550000,0,1,False,True,False,False
3,104,Male,6.8,2,78,Not Placed,0,1,0,False,False,False,True
4,105,Female,8.7,0,88,Placed,480000,0,1,True,False,False,False
5,106,Male,7.2,3,72,Not Placed,0,1,0,False,False,False,False
6,107,Female,8.9,0,91,Placed,500000,0,1,False,False,True,False
7,108,Male,6.5,1,80,Not Placed,0,1,0,True,False,False,False
8,109,Female,7.8,0,84,Placed,420000,0,1,False,True,False,False
9,110,Male,7.0,2,76,Not Placed,0,1,0,False,False,False,True